package com.mipstranslator;
import java_cup.runtime.*;
import java.util.*;

parser code {:
    private ArrayList<TablaSimbolos> Tablas = new ArrayList<>();
    private TablaSimbolos TablaActual = null;

    private AdministradorRegistrosFlotantes AdminFlotante = new AdministradorRegistrosFlotantes();
    private AdministradorRegistrosEnteros AdminEntero = new AdministradorRegistrosEnteros();

    private ArrayList<String> Data = new ArrayList<>();

    private void AgregarTablaSimbolos(String nombre){
        TablaSimbolos nuevaTabla = new TablaSimbolos(nombre, TablaActual);
        Tablas.add(nuevaTabla);
        TablaActual = nuevaTabla;
    }

    private void AsignarEnteroTemporal(String temporalIntermedio, String entero){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        InstruccionMIPS instruccion = new InstruccionAsignacionTemporalLiteral(temporalMIPS, entero);
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarFloatTemporal(String temporalIntermedio, String flotante){
        String temporalMIPS = AdminFlotante.RegistrarRegistro(temporalIntermedio);
        Float numero = Float.parseFloat(flotante);
        Integer bits = Float.floatToIntBits(numero);
        InstruccionMIPS instruccion = new InstruccionAsignacionTemporalLiteral(temporalMIPS, bits.toString());
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarCharTemporal(String temporalIntermedio, String caracter){
        String temporalMIPSFlotante = AdminFlotante.RegistrarRegistro(temporalIntermedio);
        String temporalMIPSEntero = AdminEntero.RegistrarRegistro(temporalIntermedio);
        String texto = "Hola";
        char c = caracter.charAt(0);
        Integer ascii = (int) c;
        String caracterAscii = ascii.toString();
        InstruccionMIPS instruccion = new InstruccionRegistroTemporalFlotante(temporalMIPSEntero, temporalMIPSFlotante, caracterAscii);
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarBooleanoTemporal(String temporalIntermedio, String booleano){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        String booleanoMIPS = "0";
        if(booleano.equals("luna"))
            booleanoMIPS = "1";
        InstruccionMIPS instruccion = new InstruccionAsignacionTemporalLiteral(temporalMIPS, booleanoMIPS);
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarStringTemporal(String temporalIntermedio, String string){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        String nombre = "msg" + Data.size();
        InstruccionMIPS declaracionDato = new InstruccionAsignarStringData(nombre, string);
        Data.add(declaracionDato.toString());
        InstruccionMIPS instruccion = new InstruccionCargarDireccionMemoria(temporalMIPS, nombre);
        TablaActual.AgregarInstruccion(instruccion);
    }   
:}

// === Terminales ===
terminal INT_LITERAL, FLOAT_LITERAL, BOOLEAN_LITERAL, STRING_LITERAL, CHAR_LITERAL;
terminal TEMP, ID;
terminal INT, FLOAT, BOOLEAN, CHAR, STRING;
terminal POW, ADD, SUB, MUL, DIV, MOD;
terminal AND, OR, NOT;
terminal EQ, NEQ, LE, LT, GE, GT;
terminal ASSIGN;
terminal LBRACK, RBRACK, PIPE, COMMA;
terminal LOAD, STORE, COPY, PARAM, CALL, RETURN, GOTO, IF, IFFALSE;
terminal READ_INT, READ_FLOAT, WRITE_INT, WRITE_FLOAT, WRITE_STRING, WRITE_BOOLEAN;
terminal COLON;

// === No terminales ===
non terminal programa, bloqueInstrucciones;
non terminal instruccion, expresion, tipo, literal, identificador, temporal;
non terminal declaracion, asignacion, declaracionArreglo, copiaArreglo, guardarEnArreglo, cargarDeArreglo;
non terminal llamadaFuncion, parametro, retorno;
non terminal escritura, lectura;
non terminal instruccionCondicional, instruccionGoto, etiqueta;
non terminal numeros, expresionLiteral;
non terminal llamadaFuncionConAsignacion;

// === Inicio ===
start with programa;

// === Reglas ===
programa ::= bloqueInstrucciones;

bloqueInstrucciones ::= instruccion bloqueInstrucciones
                      | instruccion;

instruccion ::= declaracion
              | asignacion
              | declaracionArreglo
              | guardarEnArreglo
              | cargarDeArreglo
              | copiaArreglo
              | escritura
              | lectura
              | llamadaFuncion
              | llamadaFuncionConAsignacion
              | retorno
              | instruccionGoto
              | instruccionCondicional
              | etiqueta
              | parametro;

// === Declaraciones y asignaciones ===
declaracion ::=
    tipo:nombreTipo identificador:nombre
{:
    if(TablaActual != null && nombreTipo != null && nombre != null){
        LineaTabla linea = new LineaTabla(nombre.toString(), nombreTipo.toString(), 0);
        TablaActual.AgregarVariable(linea);
    }
:}
    | tipo:tipoAux identificador:idAux LBRACK temporal:tempAux RBRACK
{:
    if(TablaActual != null && tipoAux != null && idAux != null && tempAux != null){
        LineaTabla linea = new LineaTabla(idAux.toString(), tipoAux.toString(), 0);
        TablaActual.AgregarVariable(linea);
    }
:};

asignacion ::=
    temporal:tempAux ASSIGN expresionLiteral:exprAux
{:
    if(TablaActual != null && tempAux != null && exprAux != null){
        String temp = tempAux.toString();
        String[] expr = (String[]) exprAux;
        if(expr[0].equals("int") ){
            AsignarEnteroTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("float")){
            AsignarFloatTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("char")){
            AsignarCharTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("boolean")){
            AsignarBooleanoTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("string")){
            AsignarStringTemporal(temp, expr[1]);
        }
    }
:}
    | identificador:idAux ASSIGN temporal:tempAux
{:
    if(idAux != null && tempAux != null && TablaActual != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String temporal = "";
        if(linea.getTipo().equals("float")){
            temporal = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp);
        }
        else{
            temporal = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        }
        InstruccionMIPS instruccion = new InstruccionCargarEnPila(temporal, linea.getDireccionRelativa().toString());
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
    | identificador:idAux LBRACK temporal:indiceAux RBRACK ASSIGN temporal:tempAux
{:
    if(idAux != null && tempAux != null && TablaActual != null && indiceAux != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        String indice = indiceAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String temporal = "";
        if(linea.getTipo().equals("float")){
            temporal = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp);
        }
        else{
            temporal = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        }
        String indiceMIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(indice);
        InstruccionMIPS instruccion = new InstruccionCargarEnteroArreglo(temporal, linea.getDireccionRelativa().toString(), indice);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

identificador ::= ID:name
{:
    if(name != null)
        RESULT = name.toString();
:};

temporal ::= TEMP:temp
{:
    if(temp != null)
        RESULT = temp.toString();
:};

tipo ::= INT:tipo
{:
    if(tipo != null){
        RESULT = tipo.toString();
    }
:}
      | FLOAT:tipo
{:
    if(tipo != null){
        RESULT = tipo.toString();
    }
:}
      | BOOLEAN:tipo
{:
    if(tipo != null){
        RESULT = tipo.toString();
    }
:}
      | CHAR:tipo
{:
    if(tipo != null){
        RESULT = tipo.toString();
    }
:}
      | STRING:tipo
{:
    if(tipo != null){
        RESULT = tipo.toString();
    }
:};

literal ::= INT_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"int", literal.toString()};
    }
:}
         | FLOAT_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"float", literal.toString()};
    }
:}
         | BOOLEAN_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"boolean", literal.toString()};
    }
:}
         | STRING_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"string", literal.toString()};
    }
:}
         | CHAR_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"char", literal.toString()};
    }
:};

// === Arreglos ===
declaracionArreglo ::= tipo identificador LBRACK expresion RBRACK;
copiaArreglo ::= COPY identificador COMMA ID;
guardarEnArreglo ::= STORE identificador LBRACK temporal RBRACK COMMA temporal;
cargarDeArreglo ::= LOAD temporal COMMA identificador LBRACK temporal RBRACK;

// === Escritura y lectura ===
escritura ::= WRITE_STRING temporal
            | WRITE_INT temporal
            | WRITE_FLOAT temporal
            | WRITE_BOOLEAN temporal;

lectura ::= READ_INT temporal
          | READ_FLOAT temporal;

parametro ::= PARAM tipo identificador;

llamadaFuncion ::= CALL ID COMMA INT_LITERAL;

llamadaFuncionConAsignacion ::= temporal ASSIGN CALL ID COMMA INT_LITERAL;

retorno ::= RETURN temporal;

expresionLiteral ::= literal
                    |identificador
                    |temporal
                    |PIPE numeros PIPE;

numeros ::= INT_LITERAL COMMA numeros
            | ;

// === Operaciones ===
expresion ::= temporal ADD temporal
            | temporal SUB temporal
            | temporal MUL temporal
            | temporal DIV temporal
            | temporal MOD temporal
            | temporal POW temporal
            | temporal EQ temporal
            | temporal NEQ temporal
            | temporal LE temporal
            | temporal LT temporal
            | temporal GE temporal
            | temporal GT temporal
            | temporal AND temporal
            | temporal OR temporal
            | NOT temporal;

// === Control de flujo ===
instruccionCondicional ::= IF expresion GOTO ID
                        | IFFALSE expresion GOTO ID;

instruccionGoto ::= GOTO ID;

etiqueta ::= ID COLON;
