package com.mipstranslator;
import java_cup.runtime.*;
import java.util.*;

parser code {:
    private ArrayList<TablaSimbolos> Tablas = new ArrayList<>();
    private ArrayList<String> codigoIntermedio = new ArrayList<>();
    private TablaSimbolos TablaActual = null;

    private Integer LineaCodigoIntermedio = 1;

    private Integer ContadorParametrosSalida = 1;

    private AdministradorRegistrosFlotantes AdminFlotante = new AdministradorRegistrosFlotantes();
    private AdministradorRegistrosEnteros AdminEntero = new AdministradorRegistrosEnteros();

    private InstruccionCrearArreglo InstruccionArregloActual = null;

    private ArrayList<String> Data = new ArrayList<>();

    private void AgregarTablaSimbolos(String nombre){
        TablaSimbolos nuevaTabla = new TablaSimbolos(nombre, TablaActual);
        Tablas.add(nuevaTabla);
        TablaActual = nuevaTabla;
    }

    public String traducirACodigoMIPS() {
        AnalizadorCodigoIntermedio analizador = new AnalizadorCodigoIntermedio(Data, Tablas);
        String codigoMIPS = analizador.generarCodigoMIPS();
        return codigoMIPS;
    }

    private void AsignarEnteroTemporal(String temporalIntermedio, String entero){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        InstruccionMIPS instruccion = new InstruccionAsignacionLiteralEntero(temporalMIPS, entero);
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarFloatTemporal(String temporalIntermedio, String flotante){
        String temporalMIPSFlotante = AdminFlotante.RegistrarRegistro(temporalIntermedio);
        String temporalMIPSEntero = AdminEntero.RegistrarRegistro("");
        Float numero = Float.parseFloat(flotante);
        Integer bits = Float.floatToIntBits(numero);
        InstruccionMIPS instruccion = new InstruccionAsignacionLiteralFlotante(temporalMIPSEntero, temporalMIPSFlotante, bits.toString());
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarCharTemporal(String temporalIntermedio, String caracter){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        char c = caracter.charAt(0);
        Integer ascii = (int) c;
        String caracterAscii = ascii.toString();
        InstruccionMIPS instruccion = new InstruccionAsignacionLiteralEntero(temporalMIPS, caracterAscii);
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarBooleanoTemporal(String temporalIntermedio, String booleano){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        String booleanoMIPS = "0";
        if(booleano.equals("luna"))
            booleanoMIPS = "1";
        InstruccionMIPS instruccion = new InstruccionAsignacionLiteralEntero(temporalMIPS, booleanoMIPS);
        TablaActual.AgregarInstruccion(instruccion);
    }

    private void AsignarStringTemporal(String temporalIntermedio, String string){
        String temporalMIPS = AdminEntero.RegistrarRegistro(temporalIntermedio);
        String nombre = "msg" + Data.size();
        InstruccionMIPS declaracionDato = new InstruccionAsignarStringData(nombre, string);
        Data.add(declaracionDato.toString());
        InstruccionMIPS instruccion = new InstruccionAsignacionLiteralString(temporalMIPS, nombre);
        TablaActual.AgregarInstruccion(instruccion);
    }

    /**
     * Maneja errores sintacticos encontrados por el parser
     * @param s simbolo donde ocurrio el error
     */
    public void syntax_error(Symbol s) {
        if (s != null) {
            System.out.println("Error sintactico en la linea " + (s.left + 1) +
            ", columna " + (s.right + 1) + ": " + s.value);
        }
    }
:}

// === Terminales ===
terminal INT_LITERAL, FLOAT_LITERAL, BOOLEAN_LITERAL, STRING_LITERAL, CHAR_LITERAL;
terminal TEMP, ID, FUNCION;
terminal INT, FLOAT, BOOLEAN, CHAR, STRING, INTARRAY;
terminal POW, ADD, SUB, MUL, DIV, MOD;
terminal AND, OR, NOT;
terminal EQ, NEQ, LE, LT, GE, GT;
terminal ASSIGN;
terminal LBRACK, RBRACK, PIPE, COMMA;
terminal LOAD, STORE, COPY, PARAM, CALL, RETURN, GOTO, IF, IFFALSE;
terminal READ_INT, READ_FLOAT, WRITE_INT, WRITE_FLOAT, WRITE_STRING, WRITE_BOOLEAN;
terminal COLON;

// === No terminales ===
non terminal programa, bloqueInstrucciones;
non terminal instruccion, expresion, tipo, literal, identificador, temporal;
non terminal declaracion, asignacion, declaracionArreglo, copiaArreglo, guardarEnArreglo, cargarDeArreglo;
non terminal parametroEntrada, parametroSalida, retorno, inicioFuncion;
non terminal escritura, lectura;
non terminal instruccionCondicional, instruccionGoto, etiqueta;
non terminal numeros;
non terminal llamadaFuncionConAsignacion;

// === Inicio ===
start with programa;

// === Reglas ===
programa ::= bloqueInstrucciones;

bloqueInstrucciones ::= instruccion  bloqueInstrucciones
                      | instruccion;

instruccion ::= 
                declaracion
              | asignacion
              | declaracionArreglo
              | guardarEnArreglo
              | cargarDeArreglo
              | copiaArreglo
              | escritura
              | lectura
              | llamadaFuncionConAsignacion
              | retorno
              | instruccionGoto
              | instruccionCondicional
              | etiqueta
              | parametroEntrada
              | parametroSalida
              | expresion
              | inicioFuncion
              | error;

// === Declaraciones y asignaciones ===
declaracion ::=
    tipo:nombreTipo identificador:nombre
{:
    if(TablaActual != null && nombreTipo != null && nombre != null){
        LineaTabla linea = new LineaTabla(nombre.toString(), nombreTipo.toString(), 0);
        TablaActual.AgregarVariable(linea);
    }
:};

asignacion ::=
    temporal:tempAux ASSIGN literal:exprAux
{:
    if(TablaActual != null && tempAux != null && exprAux != null){
        String temp = tempAux.toString();
        String[] expr = (String[]) exprAux;
        if(expr[0].equals("int") ){
            AsignarEnteroTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("float")){
            AsignarFloatTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("char")){
            AsignarCharTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("boolean")){
            AsignarBooleanoTemporal(temp, expr[1]);
        }
        else if(expr[0].equals("string")){
            AsignarStringTemporal(temp, expr[1]);
        }
    }
:}
    | identificador:idAux ASSIGN temporal:tempAux
{:
    if(idAux != null && tempAux != null && TablaActual != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String temporal = "";
        InstruccionMIPS instruccion = null;
        if(linea.getTipo().equals("float")){
            temporal = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp);
            instruccion = new InstruccionCargarEnPilaFlotante(temporal, linea.getDireccionRelativa().toString());
        }
        else{
            temporal = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
            instruccion = new InstruccionCargarEnPilaEntero(temporal, linea.getDireccionRelativa().toString());
        }
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
    | temporal:tempAux ASSIGN identificador:idAux
{:
    if(idAux != null && tempAux != null && TablaActual != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String temporal = "";
        InstruccionMIPS instruccion = null;
        if(linea.getTipo().equals("float")){
            temporal = AdminFlotante.RegistrarRegistro(temp);
            instruccion = new InstruccionTraerDePilaFlotante(temporal, linea.getDireccionRelativa().toString());
        }
        else{
            temporal = AdminEntero.RegistrarRegistro(temp);
            instruccion = new InstruccionTraerDePilaEntero(temporal, linea.getDireccionRelativa().toString());
        }
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
    | temporal:tempAux ASSIGN PIPE
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        InstruccionCrearArreglo instruccion = new InstruccionCrearArreglo(AdminEntero, "0", temp);
        TablaActual.AgregarInstruccion(instruccion);
        InstruccionArregloActual = instruccion;
    }
:}
      numeros PIPE;

numeros ::= INT_LITERAL:numeroAux
{:
    if(TablaActual != null && numeroAux != null){
        InstruccionArregloActual.AgregarNumero(numeroAux.toString());
    }
:} COMMA numeros
            | INT_LITERAL:numeroAux
{:
    if(TablaActual != null && numeroAux != null){
        InstruccionArregloActual.AgregarNumero(numeroAux.toString());
    }
:};

identificador ::= ID:name
{:
    if(name != null)
        RESULT = name.toString();
:};

temporal ::= TEMP:temp
{:
    if(temp != null)
        RESULT = temp.toString();
:};

tipo ::= INT:tipo
{:
    if(tipo != null){
        RESULT = "int";
    }
:}
      | FLOAT:tipo
{:
    if(tipo != null){
        RESULT = "float";
    }
:}
      | BOOLEAN:tipo
{:
    if(tipo != null){
        RESULT = "boolean";
    }
:}
      | CHAR:tipo
{:
    if(tipo != null){
        RESULT = "char";
    }
:}
      | STRING:tipo
{:
    if(tipo != null){
        RESULT = "string";
    }
:}
      |INTARRAY:tipo
{:
    if(tipo != null){
        RESULT = "intArray";
    }
:};

literal ::= INT_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"int", literal.toString()};
    }
:}
         | FLOAT_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"float", literal.toString()};
    }
:}
         | BOOLEAN_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"boolean", literal.toString()};
    }
:}
         | STRING_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"string", literal.toString()};
    }
:}
         | CHAR_LITERAL:literal
{:
    if(literal != null){
        RESULT = new String[]{"char", literal.toString()};
    }
:};

// === Arreglos ===
declaracionArreglo ::= tipo:tipoAux identificador:idAux LBRACK temporal:tempAux RBRACK
{:
    if(TablaActual != null && tipoAux != null && idAux != null && tempAux != null){
        LineaTabla linea = new LineaTabla(idAux.toString(), tipoAux.toString(), 0);
        TablaActual.AgregarVariable(linea);
    }
:};

copiaArreglo ::= COPY identificador:idAux COMMA temporal:tempAux
{:
    if(idAux != null && tempAux != null && TablaActual != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String temporal = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionCargarEnPilaEntero(temporal, linea.getDireccionRelativa().toString());
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

guardarEnArreglo ::= STORE identificador:idAux LBRACK temporal:indiceAux RBRACK COMMA temporal:tempAux
{:
    if(idAux != null && indiceAux != null && tempAux != null && TablaActual != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        String indice = indiceAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String valorGuardar = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        String valorIndice = AdminEntero.ObtenerRegistroMIPSDeIntermedio(indice);
        InstruccionMIPS instruccion = new GuardarEnArreglo(linea.getDireccionRelativa().toString(), valorIndice, valorGuardar);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

cargarDeArreglo ::= LOAD temporal:tempAux COMMA identificador:idAux LBRACK temporal:indiceAux RBRACK
{:
    if(idAux != null && indiceAux != null && tempAux != null && TablaActual != null){
        String id = idAux.toString();
        String temp = tempAux.toString();
        String indice = indiceAux.toString();
        LineaTabla linea = TablaActual.ObtenerVariable(id);
        String valorCargar = AdminEntero.RegistrarRegistro(temp);
        String valorIndice = AdminEntero.ObtenerRegistroMIPSDeIntermedio(indice);
        InstruccionMIPS instruccion = new CargarDeArreglo(linea.getDireccionRelativa().toString(), valorIndice, valorCargar);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

// === Escritura y lectura ===
escritura ::= WRITE_STRING temporal:tempAux
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String valorImprimir = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionEscribirString(valorImprimir);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
            | WRITE_INT temporal:tempAux
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String valorImprimir = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionEscribirEntero(valorImprimir);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
            | WRITE_FLOAT temporal:tempAux
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String valorImprimir = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionEscribirFlotante(valorImprimir);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
            | WRITE_BOOLEAN temporal:tempAux
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String valorImprimir = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionEscribirBooleano(valorImprimir);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

lectura ::= READ_INT temporal:tempAux
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String valorImprimir = AdminEntero.RegistrarRegistro(temp);
        InstruccionMIPS instruccion = new InstruccionLeerEntero(valorImprimir);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
          | READ_FLOAT temporal:tempAux
{:
    if(tempAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String valorImprimir = AdminFlotante.RegistrarRegistro(temp);
        InstruccionMIPS instruccion = new InstruccionLeerFlotante(valorImprimir);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

parametroEntrada ::= PARAM INT_LITERAL:numero tipo:nombreTipoAux identificador:idAux
{:
    if(nombreTipoAux != null && idAux != null && TablaActual != null){
        String nombreTipo = nombreTipoAux.toString();
        String id = idAux.toString();
        LineaTabla linea = new LineaTabla(id, nombreTipo, 0);
        TablaActual.AgregarParametro(linea);
    }
:};

parametroSalida ::= PARAM tipo:nombreTipoAux temporal:tempAux
{:
    if(nombreTipoAux != null && tempAux != null && TablaActual != null){
        String nombreTipo = nombreTipoAux.toString();
        String temp = tempAux.toString();
        if(ContadorParametrosSalida == 1){
            InstruccionMIPS instruccion = new InstruccionParametroSalidaEntero(ContadorParametrosSalida.toString(), "fp");
            TablaActual.AgregarInstruccion(instruccion);
            ContadorParametrosSalida++;
        }
        if(nombreTipo.equals("float")){
            String temporalMIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp);
            InstruccionMIPS instruccion = new InstruccionParametroSalidaFlotante(ContadorParametrosSalida.toString(), temporalMIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String temporalMIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
            InstruccionMIPS instruccion = new InstruccionParametroSalidaEntero(ContadorParametrosSalida.toString(), temporalMIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        ContadorParametrosSalida++;
    }
:};

llamadaFuncionConAsignacion ::= temporal:tempAux ASSIGN CALL tipo:nombreTipoAux identificador:nombre COMMA INT_LITERAL:cantidad
{:
    if(tempAux != null && nombreTipoAux != null && nombre != null && cantidad != null && TablaActual != null){
        ContadorParametrosSalida = 1;
        String nombreFuncion = nombre.toString();
        String cantParametros = cantidad.toString();
        String nombreTipo = nombreTipoAux.toString();
        String temp = tempAux.toString();
        if(nombreTipo.equals("float")){
            String temporalMIPS = AdminFlotante.RegistrarRegistro(temp);
            InstruccionMIPS instruccion = new InstruccionFuncionCallFlotante(nombreFuncion, cantParametros, temporalMIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String temporalMIPS = AdminEntero.RegistrarRegistro(temp);
            InstruccionMIPS instruccion = new InstruccionFuncionCallEntero(nombreFuncion, cantParametros, temporalMIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:};

retorno ::= RETURN tipo:nombreTipoAux temporal:tempAux
{:
    if(tempAux != null && nombreTipoAux != null && TablaActual != null){
        ContadorParametrosSalida = 1;
        String nombreTipo = nombreTipoAux.toString();
        String temp = tempAux.toString();
        if(nombreTipo.equals("float")){
            String temporalMIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp);
            InstruccionMIPS instruccion = new InstruccionRetornoFlotante(temporalMIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String temporalMIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
            InstruccionMIPS instruccion = new InstruccionRetornoEntero(temporalMIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:};

// === Operaciones ===
expresion ::= temporal:tempDestinoAux ASSIGN temporal:tempAux1 ADD temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("add", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String tempDestinoMIPS = AdminFlotante.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("add.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 SUB temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("sub", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String tempDestinoMIPS = AdminFlotante.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("sub.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 MUL temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("mul", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String tempDestinoMIPS = AdminFlotante.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("mul.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 DIV temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("div", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String tempDestinoMIPS = AdminFlotante.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionOperacionMatematica("div.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 MOD temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
        String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
        String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
        InstruccionMIPS instruccion = new InstruccionOperacionMatematica("rem", tempDestinoMIPS, temp1MIPS, temp2MIPS);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 POW temporal:tempAux2
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 EQ  temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion1 = new InstruccionComparacionEntero("xor", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion1);
            InstruccionMIPS instruccion2 = new InstruccionComparacionEnteroSecundario("sltiu", tempDestinoMIPS, tempDestinoMIPS, "1");
            TablaActual.AgregarInstruccion(instruccion2);
        }
        else{
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionFlotante("c.eq.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 NEQ temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion1 = new InstruccionComparacionEntero("xor", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion1);
            InstruccionMIPS instruccion2 = new InstruccionComparacionEntero("sltu", tempDestinoMIPS, "zero", tempDestinoMIPS);
            TablaActual.AgregarInstruccion(instruccion2);
        }
        else{
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionFlotanteInverso("c.eq.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 LE  temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion1 = new InstruccionComparacionEntero("slt", tempDestinoMIPS, temp2MIPS, temp1MIPS);
            TablaActual.AgregarInstruccion(instruccion1);
            InstruccionMIPS instruccion2 = new InstruccionComparacionEnteroSecundario("xori", tempDestinoMIPS, tempDestinoMIPS, "1");
            TablaActual.AgregarInstruccion(instruccion2);
        }
        else{
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionFlotante("c.le.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 LT  temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionEntero("slt", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionFlotante("c.lt.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 GE  temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion1 = new InstruccionComparacionEntero("slt", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion1);
            InstruccionMIPS instruccion2 = new InstruccionComparacionEnteroSecundario("xori", tempDestinoMIPS, tempDestinoMIPS, "1");
            TablaActual.AgregarInstruccion(instruccion2);
        }
        else{
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionFlotanteInverso("c.le.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 GT  temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        if(AdminEntero.VerificarExistenciaRegistro(temp1)){
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionEntero("sge", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
        else{
            String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
            String temp1MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp1);
            String temp2MIPS = AdminFlotante.ObtenerRegistroMIPSDeIntermedio(temp2);
            InstruccionMIPS instruccion = new InstruccionComparacionFlotanteInverso("c.lt.s", tempDestinoMIPS, temp1MIPS, temp2MIPS);
            TablaActual.AgregarInstruccion(instruccion);
        }
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 AND temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
        String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
        String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
        InstruccionMIPS instruccion = new InstruccionComparacionEntero("and", tempDestinoMIPS, temp1MIPS, temp2MIPS);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
            | temporal:tempDestinoAux ASSIGN temporal:tempAux1 OR  temporal:tempAux2
{:
    if(tempDestinoAux != null && tempAux1 != null && tempAux2 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String temp2 = tempAux2.toString();
        String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
        String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
        String temp2MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp2);
        InstruccionMIPS instruccion = new InstruccionComparacionEntero("or", tempDestinoMIPS, temp1MIPS, temp2MIPS);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
            | temporal:tempDestinoAux ASSIGN NOT temporal:tempAux1
{:
    if(tempDestinoAux != null && tempAux1 != null && TablaActual != null){
        String tempDestino = tempDestinoAux.toString();
        String temp1 = tempAux1.toString();
        String tempDestinoMIPS = AdminEntero.RegistrarRegistro(tempDestino);
        String temp1MIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp1);
        InstruccionMIPS instruccion = new InstruccionComparacionEntero("nor", tempDestinoMIPS, temp1MIPS, temp1MIPS);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};



// === Control de flujo ===
instruccionCondicional ::= IF temporal:tempAux GOTO identificador:idAux
{:
    if(tempAux != null && idAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String id = idAux.toString();
        String tempDestinoMIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionIfGoto(tempDestinoMIPS, id);
        TablaActual.AgregarInstruccion(instruccion);
    }
:}
                        | IFFALSE temporal:tempAux GOTO identificador:idAux
{:
    if(tempAux != null && idAux != null && TablaActual != null){
        String temp = tempAux.toString();
        String id = idAux.toString();
        String tempDestinoMIPS = AdminEntero.ObtenerRegistroMIPSDeIntermedio(temp);
        InstruccionMIPS instruccion = new InstruccionIfFalseGoto(tempDestinoMIPS, id);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

instruccionGoto ::= GOTO identificador:idAux
{:
    if(idAux != null && TablaActual != null){
        String id = idAux.toString();
        InstruccionMIPS instruccion = new InstruccionGoto(id);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

etiqueta ::= identificador:idAux COLON
{:
    if(idAux != null && TablaActual != null){
        String id = idAux.toString();
        InstruccionMIPS instruccion = new InstruccionEtiqueta(id);
        TablaActual.AgregarInstruccion(instruccion);
    }
:};

inicioFuncion ::= FUNCION identificador:idAux COLON
{:
    if(idAux != null){
        TablaSimbolos tabla = new TablaSimbolos(idAux.toString(), null);
        TablaActual = tabla;
        Tablas.add(tabla);
    }
:};