
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mipstranslator;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 14;
  public static final int STRING_LITERAL = 5;
  public static final int CHAR = 12;
  public static final int GE = 27;
  public static final int CHAR_LITERAL = 6;
  public static final int WRITE_STRING = 47;
  public static final int LOAD = 34;
  public static final int STORE = 35;
  public static final int INT = 9;
  public static final int IFFALSE = 42;
  public static final int PARAM = 37;
  public static final int BOOLEAN_LITERAL = 4;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int COPY = 36;
  public static final int LT = 26;
  public static final int WRITE_INT = 45;
  public static final int OR = 21;
  public static final int COMMA = 33;
  public static final int CALL = 38;
  public static final int DIV = 18;
  public static final int IF = 41;
  public static final int ASSIGN = 29;
  public static final int ID = 8;
  public static final int LE = 25;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int READ_FLOAT = 44;
  public static final int RETURN = 39;
  public static final int TEMP = 7;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int PIPE = 32;
  public static final int ADD = 15;
  public static final int MOD = 19;
  public static final int NEQ = 24;
  public static final int EQ = 23;
  public static final int LBRACK = 30;
  public static final int COLON = 49;
  public static final int WRITE_FLOAT = 46;
  public static final int READ_INT = 43;
  public static final int RBRACK = 31;
  public static final int GOTO = 40;
  public static final int WRITE_BOOLEAN = 48;
  public static final int FLOAT = 10;
  public static final int STRING = 13;
  public static final int FLOAT_LITERAL = 3;
  public static final int GT = 28;
  public static final int SUB = 16;
  public static final int INT_LITERAL = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "BOOLEAN_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "TEMP",
  "ID",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "POW",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "NEQ",
  "LE",
  "LT",
  "GE",
  "GT",
  "ASSIGN",
  "LBRACK",
  "RBRACK",
  "PIPE",
  "COMMA",
  "LOAD",
  "STORE",
  "COPY",
  "PARAM",
  "CALL",
  "RETURN",
  "GOTO",
  "IF",
  "IFFALSE",
  "READ_INT",
  "READ_FLOAT",
  "WRITE_INT",
  "WRITE_FLOAT",
  "WRITE_STRING",
  "WRITE_BOOLEAN",
  "COLON"
  };
}

